### ISSUE TITLE
Setting the time zone fails depending on what machine is running Vagrant

### ISSUE THREAD

**Issue by evarga** [tmatilai/vagrant-timezone#3] opened 2015-12-04 17:43 UTC
I was able to successfully set the time zone of a host in the AWS cloud using my `Vagrantfile` (based on the `vagrant-aws` plugin) and the `vagrant-timezone` plugin (`vagrant up` was run on my Mac OS X Yosemite). However, when I try to run the same Vagrantfile with the same version of Vagrant on an Ubuntu 14.04 machine then I get the following error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

dpkg-reconfigure --frontend noninteractive tzdata

Stdout from the command:

Stderr from the command:

sudo: unable to resolve host ip-172-31-128-199
stdin: is not a tty
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
```

Any idea? Thanks!

**Comment by tmatilai** [comment] 2015-12-05 07:30
There seems to be another process running apt/dpkg/debconf. Maybe something in the user data script? In that case not sure how to address that. Maybe just trying again. You can of course run `vagrant provision` manually, too.

**Comment by evarga** [comment] 2015-12-05 10:02
Thanks for the reply! There is nothing in the user_data section. What is puzzling that by running the same Vagrantfile on different machines I get this behavior. I will look into your source code when I get time to see what is happening under the hood.

**Comment by tmatilai** [comment] 2015-12-05 11:15
If you gist all the output of `vagrant up --debug`, I can also try to see if I can spot the issue.

**Comment by evarga** [comment] 2015-12-05 17:01
I have solved the issue by directly putting the following statement as EC2 user data (following the advice from this thread: https://github.com/docker/docker/issues/3359):
```
echo <my time zone> | sudo tee /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata
```
What I have noticed is that in your code echoing into `/etc/timezone` is done separately from `dpkg-reconfigure`. When I try the `echo` part only on Ubuntu I get the following error:
```
ubuntu@ip-172-31-128-85:~$ sudo echo GMT > /etc/timezone
-bash: /etc/timezone: Permission denied
```

**Comment by tmatilai** [comment] 2015-12-05 17:55
The underlying issue still is that something else is also running debconf at the same time as this plugin tries to do the magic. Maybe then some init script or a like?

> `sudo echo GMT > /etc/timezone`

This does not work as your shell tries to open the file with your current user's permissions, and only runs the `echo` command with sudo. Vagrant (well, that `comm.sudo`) anyway wraps the whole line, including the redirection, in sudo, so that is not the issue here.

**Comment by evarga** [comment] 2015-12-05 18:03
Yeah, I know, just wanted to give more examples here into the picture. The summary is that the same Vagrantfile run with the same Vagrant 1.7.4 on Mac OS X and Ubuntu 14.04 behaves differently. This is strange. Therefore, no init script or anything similar should be running, as once again, I am provisioning with the same Vagrantfile using the aws provider. If there would be any difference in the guest OS then I would have to get the same error when starting the process on my Mac.

At any rate, thanks for the help! I think, I will go forward with putting that statement into EC2 user data, as it works for now perfectly in my case.

**Comment by tmatilai** [comment] 2015-12-05 18:11
Unless you use the `:host` setting, there shouldn't be anything host specific in this plugin. And even the `:host` for sure wouldn't be the cause. Maybe another plugin?

For me the only way forward would be the debug logs. Otherwise I'm tempted to close the issue especially as you have found a workaround that suits you.

**Comment by evarga** [comment] 2015-12-05 18:43
I am not using the `:host` setting. Ok, you may close this issue. I opened it to see whether maybe you have some quick asnwer what might be wrong. But I would not like you to spend too much time on this. I have also found a workaround, so I am good. Thanks again!

**Comment by tmatilai** [comment] 2015-12-05 19:49
No problem. Feel free to reopen if needed.

**Closed by tmatilai** 2015-12-05 19:49 UTC
